services:
  - type: web
    name: ghostsystems
    env: node
    plan: free              # or starter / pro if you upgrade later
    rootDir: ./             # tells Render to build from repo root
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GHOST_MODE
        value: learning
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GUMROAD_API_KEY
        sync: false
      - key: GUMROAD_WEBHOOK_SECRET
        sync: false
      - key: LEMONSQUEEZY_API_KEY
        sync: false
      - key: LEMONSQUEEZY_STORE_ID
        sync: false
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DB_PRODUCTS_ID
        sync: false

  # Optional background cron-runner (comment out if not needed)
  - type: worker
    name: ghostsystems-cron
    env: node
    rootDir: ./
    buildCommand: npm install
    startCommand: node src/cloud/runner.js
    autoDeploy: true

