import os, json, random
from util import save_meta, sku
from pathlib import Path

MICRO_TOPICS = [
  'AI Onboarding Checklist', '30 Prompt Pack for Sales',
  'Notion CRM Template', 'Cold DM Scripts', 'B2B ICP Worksheet'
]
MACRO_TOPICS = [
  'AI Ops Playbook (90-Minute Course)', 'Autonomous Marketing Toolkit',
  "Founder's Automation Bootcamp", 'Cold Outreach Masterclass'
]

def gen(kind='micro'):
  title = random.choice(MICRO_TOPICS if kind=='micro' else MACRO_TOPICS)
  body = f"# {title}\\n\\n- What you get\\n- How to use\\n- Quick wins\\n\\n(Replace stub with LLM content.)"
  return title, body

def write_product(title, body, kind):
  base = Path('data/products')/kind
  base.mkdir(parents=True, exist_ok=True)
  file = base/f"{sku(title, kind)}.md"
  file.write_text(body, encoding='utf-8')
  return str(file)

def main():
  os.makedirs('data/meta', exist_ok=True)
  os.makedirs('data/media', exist_ok=True)
  kinds = ['micro','micro','micro','macro']
  for kind in kinds:
    t, b = gen(kind)
    path = write_product(t, b, kind)
    meta = {
      'sku': os.path.basename(path).replace('.md',''),
      'title': t,
      'kind': kind,
      'description': f"{t} — generated by Ghost Forge. (Stub content, replace via LLM.)",
      'price_cents': 1900 if kind=='micro' else 9900,
      'tags': ['automation','ai','playbook'] if kind=='macro' else ['template','prompt','notion'],
      'assets': [path],
      'cover': None
    }
    save_meta(meta)

if __name__ == '__main__':
  main()
